Fix mkdir typo in code which created ~/.pulp dir
Running log command caused the problems:

    $ dock-pulp.py -s myserver login -u admin -p $(PASS)
    INFO      logging in as admin
    Traceback (most recent call last):
    File ".../dockpulp/bin/dock-pulp.py", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
    File ".../dockpulp/bin/dock-pulp.py", line 596, in <module>
        main()
    File ".../dockpulp/bin/dock-pulp.py", line 47, in main
        cmd(opts, args[1:])
    File ".../dockpulp/bin/dock-pulp.py", line 361, in do_login
        os.makedir(creddir)
    AttributeError: 'module' object has no attribute 'makedir'